"""baseline: legacy schema + hot-path indexes

Revision ID: 2964177e83c3
Revises: 
Create Date: 2026-08-30 13:14:23.548114

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2964177e83c3'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliate_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('affiliate_name', sa.String(length=100), nullable=True),
    sa.Column('affiliate_email', sa.String(length=150), nullable=True),
    sa.Column('discount_percent', sa.Integer(), server_default='10', nullable=True),
    sa.Column('commission_percent', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=True),
    sa.Column('total_sales', sa.Integer(), server_default='0', nullable=True),
    sa.Column('total_revenue', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('affiliate_conversions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('affiliate_code', sa.String(length=50), nullable=True),
    sa.Column('plan_name', sa.String(length=100), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('waist', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('chest', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('arms', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('thighs', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_client_progress_client_created', 'client_progress', ['client_id', 'created_at'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('goal', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('access_token', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token'),
    sa.UniqueConstraint('email')
    )
    op.create_table('diet_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=255), nullable=True),
    sa.Column('diet_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_diet_plans_active', 'diet_plans', ['client_id', 'id'], unique=False, postgresql_where=sa.text('is_active IS true'))
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('plan_name', sa.String(length=100), nullable=True),
    sa.Column('original_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_percent', sa.Integer(), server_default='0', nullable=True),
    sa.Column('coupon_code', sa.String(length=50), nullable=True),
    sa.Column('final_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=255), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=255), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_enrollments_coupon_status', 'enrollments', ['coupon_code', 'payment_status'], unique=False)
    op.create_index('ix_enrollments_email', 'enrollments', ['email'], unique=False)
    op.create_index('ix_enrollments_payment_id', 'enrollments', ['razorpay_payment_id'], unique=False)
    op.create_table('workout_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('day_number', sa.Integer(), nullable=True),
    sa.Column('day_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workout_days_plan_daynum', 'workout_days', ['plan_id', 'day_number'], unique=False)
    op.create_table('workout_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=True),
    sa.Column('exercise_name', sa.String(length=255), nullable=True),
    sa.Column('sets_count', sa.Integer(), nullable=True),
    sa.Column('reps', sa.String(length=50), nullable=True),
    sa.Column('youtube_url', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workout_exercises_day_sort', 'workout_exercises', ['day_id', 'sort_order'], unique=False)
    op.create_table('workout_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('month_no', sa.Integer(), nullable=False),
    sa.Column('week_no', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_no', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workout_logs_user_completed_ex', 'workout_logs', ['user_email', 'exercise_id'], unique=False, postgresql_where=sa.text('completed IS true'))
    op.create_index('ix_workout_logs_user_created', 'workout_logs', ['user_email', 'created_at'], unique=False)
    op.create_table('workout_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('plan_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workout_json', sa.Text(), nullable=True),
    sa.Column('version_no', sa.Integer(), server_default='1', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workout_plans_active', 'workout_plans', ['client_id', 'id'], unique=False, postgresql_where=sa.text('is_active IS true'))
    op.create_index('ix_workout_plans_client_version', 'workout_plans', ['client_id', 'version_no'], unique=False)
    op.create_table('workout_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('set_number', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_progress')
    op.drop_index('ix_workout_plans_client_version', table_name='workout_plans')
    op.drop_index('ix_workout_plans_active', table_name='workout_plans', postgresql_where=sa.text('is_active IS true'))
    op.drop_table('workout_plans')
    op.drop_index('ix_workout_logs_user_created', table_name='workout_logs')
    op.drop_index('ix_workout_logs_user_completed_ex', table_name='workout_logs', postgresql_where=sa.text('completed IS true'))
    op.drop_table('workout_logs')
    op.drop_index('ix_workout_exercises_day_sort', table_name='workout_exercises')
    op.drop_table('workout_exercises')
    op.drop_index('ix_workout_days_plan_daynum', table_name='workout_days')
    op.drop_table('workout_days')
    op.drop_index('ix_enrollments_payment_id', table_name='enrollments')
    op.drop_index('ix_enrollments_email', table_name='enrollments')
    op.drop_index('ix_enrollments_coupon_status', table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index('ix_diet_plans_active', table_name='diet_plans', postgresql_where=sa.text('is_active IS true'))
    op.drop_table('diet_plans')
    op.drop_table('clients')
    op.drop_index('ix_client_progress_client_created', table_name='client_progress')
    op.drop_table('client_progress')
    op.drop_table('affiliate_conversions')
    op.drop_table('affiliate_codes')
    # ### end Alembic commands ###
