"""applicants table for intake submissions

Revision ID: b1a7c4d92f30
Revises: 2964177e83c3
Create Date: 2026-09-06

Written by hand rather than autogenerated: `alembic revision --autogenerate`
requires the target database to be stamped at head, and the baseline revision
creates the legacy tables that already exist on BigRock. Running it to satisfy
autogenerate would have issued DDL against live data.

The same table is created at boot by ensure_applicants_table() when
APPLICANTS_AUTO_CREATE=true. Both paths build the identical shape; this one is
for managed environments, where APPLICANTS_AUTO_CREATE should be false so the
schema only ever changes through a migration.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b1a7c4d92f30'
down_revision: str | Sequence[str] | None = '2964177e83c3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'applicants',
        sa.Column('id', sa.Integer(), nullable=False),

        # Required fields, enforced by intake_service before the insert.
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        # Strings, not numbers: the validator checks non-empty, never numeric.
        sa.Column('age', sa.String(length=10), nullable=False),
        sa.Column('weight', sa.String(length=20), nullable=False),
        sa.Column('weight_unit', sa.String(length=10), server_default='kg', nullable=False),

        # Body metrics.
        sa.Column('height_cm', sa.String(length=20), nullable=True),
        sa.Column('height_ft', sa.String(length=10), nullable=True),
        sa.Column('height_in', sa.String(length=10), nullable=True),
        sa.Column('height_unit', sa.String(length=10), server_default='cm', nullable=False),
        sa.Column('fitness_level', sa.String(length=50), nullable=True),
        sa.Column('days_per_week', sa.String(length=20), nullable=True),
        sa.Column('session_duration', sa.String(length=50), nullable=True),

        # Personal.
        sa.Column('gender', sa.String(length=50), nullable=True),
        sa.Column('occupation', sa.String(length=255), nullable=True),

        # Goals and health. Lists arrive comma-joined, matching the email.
        sa.Column('goals', sa.Text(), nullable=True),
        sa.Column('goal_focus', sa.String(length=255), nullable=True),
        sa.Column('workout_pref', sa.String(length=100), nullable=True),
        sa.Column('injuries', sa.Text(), nullable=True),
        sa.Column('injuries_detail', sa.Text(), nullable=True),

        # Diet and lifestyle.
        sa.Column('diet', sa.String(length=255), nullable=True),
        sa.Column('sleep', sa.String(length=50), nullable=True),
        sa.Column('stress', sa.String(length=50), nullable=True),
        sa.Column('consultation', sa.Boolean(), server_default='0', nullable=False),

        # Operational.
        sa.Column('created_at', sa.DateTime(timezone=True),
                  server_default=sa.text('now()'), nullable=False),
        sa.Column('source', sa.String(length=20), server_default='api', nullable=False),
        sa.Column('request_id', sa.String(length=32), nullable=True),
        sa.Column('mail_status', sa.String(length=10), nullable=True),
        # Deliberately not a FK: `clients` is legacy data this app does not own.
        sa.Column('client_id', sa.Integer(), nullable=True),

        # Retention. NULL = keep forever (a converted lead).
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),

        sa.PrimaryKeyConstraint('id'),
    )
    # Not unique: the same person may legitimately submit more than once.
    op.create_index('ix_applicants_email', 'applicants', ['email'])
    op.create_index('ix_applicants_created_at', 'applicants', ['created_at'])
    # scripts/purge_applicants.py scans on this alone.
    op.create_index('ix_applicants_expires_at', 'applicants', ['expires_at'])


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_applicants_expires_at', table_name='applicants')
    op.drop_index('ix_applicants_created_at', table_name='applicants')
    op.drop_index('ix_applicants_email', table_name='applicants')
    op.drop_table('applicants')
